# coding: utf-8

"""
    Detection On Demand

    FireEye offers a best-in-class virtual execution engine in many of its core products, including our Network Security, Email Security, and File Analysis solutions. Now our customers can interact with and consume those capabilities directly via a scalable and performant web service. Use the new RESTful API to submit files for malware analysis, search hash values for past analysis results, get full reports for your file submissions, and integrate into your existing toolsets and workflows.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: developers@fireeye.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.rate_limit_exceeded import RateLimitExceeded  # noqa: E501
from openapi_client.rest import ApiException


class TestRateLimitExceeded(unittest.TestCase):
    """RateLimitExceeded unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRateLimitExceeded(self):
        """Test RateLimitExceeded"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.rate_limit_exceeded.RateLimitExceeded()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
