# coding: utf-8

"""
    Helix API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import helix
from helix.models.inline_object91 import InlineObject91  # noqa: E501
from helix.rest import ApiException


class TestInlineObject91(unittest.TestCase):
    """InlineObject91 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineObject91(self):
        """Test InlineObject91"""
        # FIXME: construct object with mandatory attributes with example values
        # model = helix.models.inline_object91.InlineObject91()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
