# coding: utf-8

"""
    Intel API v3 - Simplified Intel API

    FireEye Intel API - Simplified Intelligence  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@fireeye.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from fireeye.intel.configuration import Configuration


class AvClassificationsFirst(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'av_vendor': 'str',
        'av_product': 'str',
        'total_malicious': 'float',
        'total_scanned': 'float',
        'first_seen': 'str'
    }

    attribute_map = {
        'id': 'id',
        'av_vendor': 'av_vendor',
        'av_product': 'av_product',
        'total_malicious': 'total_malicious',
        'total_scanned': 'total_scanned',
        'first_seen': 'first_seen'
    }

    def __init__(self, id=None, av_vendor=None, av_product=None, total_malicious=None, total_scanned=None, first_seen=None, local_vars_configuration=None):  # noqa: E501
        """AvClassificationsFirst - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._av_vendor = None
        self._av_product = None
        self._total_malicious = None
        self._total_scanned = None
        self._first_seen = None
        self.discriminator = None

        self.id = id
        self.av_vendor = av_vendor
        self.av_product = av_product
        self.total_malicious = total_malicious
        self.total_scanned = total_scanned
        if first_seen is not None:
            self.first_seen = first_seen

    @property
    def id(self):
        """Gets the id of this AvClassificationsFirst.  # noqa: E501


        :return: The id of this AvClassificationsFirst.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AvClassificationsFirst.


        :param id: The id of this AvClassificationsFirst.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def av_vendor(self):
        """Gets the av_vendor of this AvClassificationsFirst.  # noqa: E501


        :return: The av_vendor of this AvClassificationsFirst.  # noqa: E501
        :rtype: str
        """
        return self._av_vendor

    @av_vendor.setter
    def av_vendor(self, av_vendor):
        """Sets the av_vendor of this AvClassificationsFirst.


        :param av_vendor: The av_vendor of this AvClassificationsFirst.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and av_vendor is None:  # noqa: E501
            raise ValueError("Invalid value for `av_vendor`, must not be `None`")  # noqa: E501

        self._av_vendor = av_vendor

    @property
    def av_product(self):
        """Gets the av_product of this AvClassificationsFirst.  # noqa: E501


        :return: The av_product of this AvClassificationsFirst.  # noqa: E501
        :rtype: str
        """
        return self._av_product

    @av_product.setter
    def av_product(self, av_product):
        """Sets the av_product of this AvClassificationsFirst.


        :param av_product: The av_product of this AvClassificationsFirst.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and av_product is None:  # noqa: E501
            raise ValueError("Invalid value for `av_product`, must not be `None`")  # noqa: E501

        self._av_product = av_product

    @property
    def total_malicious(self):
        """Gets the total_malicious of this AvClassificationsFirst.  # noqa: E501


        :return: The total_malicious of this AvClassificationsFirst.  # noqa: E501
        :rtype: float
        """
        return self._total_malicious

    @total_malicious.setter
    def total_malicious(self, total_malicious):
        """Sets the total_malicious of this AvClassificationsFirst.


        :param total_malicious: The total_malicious of this AvClassificationsFirst.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and total_malicious is None:  # noqa: E501
            raise ValueError("Invalid value for `total_malicious`, must not be `None`")  # noqa: E501

        self._total_malicious = total_malicious

    @property
    def total_scanned(self):
        """Gets the total_scanned of this AvClassificationsFirst.  # noqa: E501


        :return: The total_scanned of this AvClassificationsFirst.  # noqa: E501
        :rtype: float
        """
        return self._total_scanned

    @total_scanned.setter
    def total_scanned(self, total_scanned):
        """Sets the total_scanned of this AvClassificationsFirst.


        :param total_scanned: The total_scanned of this AvClassificationsFirst.  # noqa: E501
        :type: float
        """
        if self.local_vars_configuration.client_side_validation and total_scanned is None:  # noqa: E501
            raise ValueError("Invalid value for `total_scanned`, must not be `None`")  # noqa: E501

        self._total_scanned = total_scanned

    @property
    def first_seen(self):
        """Gets the first_seen of this AvClassificationsFirst.  # noqa: E501


        :return: The first_seen of this AvClassificationsFirst.  # noqa: E501
        :rtype: str
        """
        return self._first_seen

    @first_seen.setter
    def first_seen(self, first_seen):
        """Sets the first_seen of this AvClassificationsFirst.


        :param first_seen: The first_seen of this AvClassificationsFirst.  # noqa: E501
        :type: str
        """

        self._first_seen = first_seen

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AvClassificationsFirst):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AvClassificationsFirst):
            return True

        return self.to_dict() != other.to_dict()
