# coding: utf-8

"""
    Intel API v3 - Simplified Intel API

    FireEye Intel API - Simplified Intelligence  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@fireeye.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from fireeye.intel.configuration import Configuration


class FindingsTelExtensions(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'average_ttl': 'FindingsTelExtensionsAverageTtl'
    }

    attribute_map = {
        'average_ttl': 'average-ttl'
    }

    def __init__(self, average_ttl=None, local_vars_configuration=None):  # noqa: E501
        """FindingsTelExtensions - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._average_ttl = None
        self.discriminator = None

        if average_ttl is not None:
            self.average_ttl = average_ttl

    @property
    def average_ttl(self):
        """Gets the average_ttl of this FindingsTelExtensions.  # noqa: E501


        :return: The average_ttl of this FindingsTelExtensions.  # noqa: E501
        :rtype: FindingsTelExtensionsAverageTtl
        """
        return self._average_ttl

    @average_ttl.setter
    def average_ttl(self, average_ttl):
        """Sets the average_ttl of this FindingsTelExtensions.


        :param average_ttl: The average_ttl of this FindingsTelExtensions.  # noqa: E501
        :type: FindingsTelExtensionsAverageTtl
        """

        self._average_ttl = average_ttl

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FindingsTelExtensions):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FindingsTelExtensions):
            return True

        return self.to_dict() != other.to_dict()
