# coding: utf-8

"""
    Intel API v3 - Simplified Intel API

    FireEye Intel API - Simplified Intelligence  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@fireeye.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from fireeye.intel.configuration import Configuration


class Ioc(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'created': 'str',
        'modified': 'str',
        'pattern': 'str',
        'labels': 'list[str]',
        'confidence': 'int',
        'name': 'str',
        'hashes': 'FileSpecificPropertiesHashes',
        'full_path': 'str',
        'size': 'int',
        'description': 'str',
        'value': 'str',
        '_from': 'str',
        'to': 'list[str]',
        'received_lines': 'list[str]',
        'label': 'str',
        'subject': 'str'
    }

    attribute_map = {
        'id': 'id',
        'created': 'created',
        'modified': 'modified',
        'pattern': 'pattern',
        'labels': 'labels',
        'confidence': 'confidence',
        'name': 'name',
        'hashes': 'hashes',
        'full_path': 'full_path',
        'size': 'size',
        'description': 'description',
        'value': 'value',
        '_from': 'from',
        'to': 'to',
        'received_lines': 'received_lines',
        'label': 'label',
        'subject': 'subject'
    }

    def __init__(self, id=None, created=None, modified=None, pattern=None, labels=None, confidence=None, name=None, hashes=None, full_path=None, size=None, description=None, value=None, _from=None, to=None, received_lines=None, label=None, subject=None, local_vars_configuration=None):  # noqa: E501
        """Ioc - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._created = None
        self._modified = None
        self._pattern = None
        self._labels = None
        self._confidence = None
        self._name = None
        self._hashes = None
        self._full_path = None
        self._size = None
        self._description = None
        self._value = None
        self.__from = None
        self._to = None
        self._received_lines = None
        self._label = None
        self._subject = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if created is not None:
            self.created = created
        if modified is not None:
            self.modified = modified
        if pattern is not None:
            self.pattern = pattern
        if labels is not None:
            self.labels = labels
        if confidence is not None:
            self.confidence = confidence
        if name is not None:
            self.name = name
        if hashes is not None:
            self.hashes = hashes
        if full_path is not None:
            self.full_path = full_path
        if size is not None:
            self.size = size
        if description is not None:
            self.description = description
        if value is not None:
            self.value = value
        if _from is not None:
            self._from = _from
        if to is not None:
            self.to = to
        if received_lines is not None:
            self.received_lines = received_lines
        if label is not None:
            self.label = label
        if subject is not None:
            self.subject = subject

    @property
    def id(self):
        """Gets the id of this Ioc.  # noqa: E501


        :return: The id of this Ioc.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Ioc.


        :param id: The id of this Ioc.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def created(self):
        """Gets the created of this Ioc.  # noqa: E501


        :return: The created of this Ioc.  # noqa: E501
        :rtype: str
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this Ioc.


        :param created: The created of this Ioc.  # noqa: E501
        :type: str
        """

        self._created = created

    @property
    def modified(self):
        """Gets the modified of this Ioc.  # noqa: E501


        :return: The modified of this Ioc.  # noqa: E501
        :rtype: str
        """
        return self._modified

    @modified.setter
    def modified(self, modified):
        """Sets the modified of this Ioc.


        :param modified: The modified of this Ioc.  # noqa: E501
        :type: str
        """

        self._modified = modified

    @property
    def pattern(self):
        """Gets the pattern of this Ioc.  # noqa: E501


        :return: The pattern of this Ioc.  # noqa: E501
        :rtype: str
        """
        return self._pattern

    @pattern.setter
    def pattern(self, pattern):
        """Sets the pattern of this Ioc.


        :param pattern: The pattern of this Ioc.  # noqa: E501
        :type: str
        """

        self._pattern = pattern

    @property
    def labels(self):
        """Gets the labels of this Ioc.  # noqa: E501


        :return: The labels of this Ioc.  # noqa: E501
        :rtype: list[str]
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this Ioc.


        :param labels: The labels of this Ioc.  # noqa: E501
        :type: list[str]
        """

        self._labels = labels

    @property
    def confidence(self):
        """Gets the confidence of this Ioc.  # noqa: E501


        :return: The confidence of this Ioc.  # noqa: E501
        :rtype: int
        """
        return self._confidence

    @confidence.setter
    def confidence(self, confidence):
        """Sets the confidence of this Ioc.


        :param confidence: The confidence of this Ioc.  # noqa: E501
        :type: int
        """

        self._confidence = confidence

    @property
    def name(self):
        """Gets the name of this Ioc.  # noqa: E501


        :return: The name of this Ioc.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Ioc.


        :param name: The name of this Ioc.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def hashes(self):
        """Gets the hashes of this Ioc.  # noqa: E501


        :return: The hashes of this Ioc.  # noqa: E501
        :rtype: FileSpecificPropertiesHashes
        """
        return self._hashes

    @hashes.setter
    def hashes(self, hashes):
        """Sets the hashes of this Ioc.


        :param hashes: The hashes of this Ioc.  # noqa: E501
        :type: FileSpecificPropertiesHashes
        """

        self._hashes = hashes

    @property
    def full_path(self):
        """Gets the full_path of this Ioc.  # noqa: E501


        :return: The full_path of this Ioc.  # noqa: E501
        :rtype: str
        """
        return self._full_path

    @full_path.setter
    def full_path(self, full_path):
        """Sets the full_path of this Ioc.


        :param full_path: The full_path of this Ioc.  # noqa: E501
        :type: str
        """

        self._full_path = full_path

    @property
    def size(self):
        """Gets the size of this Ioc.  # noqa: E501


        :return: The size of this Ioc.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this Ioc.


        :param size: The size of this Ioc.  # noqa: E501
        :type: int
        """

        self._size = size

    @property
    def description(self):
        """Gets the description of this Ioc.  # noqa: E501


        :return: The description of this Ioc.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Ioc.


        :param description: The description of this Ioc.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def value(self):
        """Gets the value of this Ioc.  # noqa: E501


        :return: The value of this Ioc.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this Ioc.


        :param value: The value of this Ioc.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def _from(self):
        """Gets the _from of this Ioc.  # noqa: E501


        :return: The _from of this Ioc.  # noqa: E501
        :rtype: str
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """Sets the _from of this Ioc.


        :param _from: The _from of this Ioc.  # noqa: E501
        :type: str
        """

        self.__from = _from

    @property
    def to(self):
        """Gets the to of this Ioc.  # noqa: E501


        :return: The to of this Ioc.  # noqa: E501
        :rtype: list[str]
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this Ioc.


        :param to: The to of this Ioc.  # noqa: E501
        :type: list[str]
        """

        self._to = to

    @property
    def received_lines(self):
        """Gets the received_lines of this Ioc.  # noqa: E501


        :return: The received_lines of this Ioc.  # noqa: E501
        :rtype: list[str]
        """
        return self._received_lines

    @received_lines.setter
    def received_lines(self, received_lines):
        """Sets the received_lines of this Ioc.


        :param received_lines: The received_lines of this Ioc.  # noqa: E501
        :type: list[str]
        """

        self._received_lines = received_lines

    @property
    def label(self):
        """Gets the label of this Ioc.  # noqa: E501


        :return: The label of this Ioc.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this Ioc.


        :param label: The label of this Ioc.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def subject(self):
        """Gets the subject of this Ioc.  # noqa: E501


        :return: The subject of this Ioc.  # noqa: E501
        :rtype: str
        """
        return self._subject

    @subject.setter
    def subject(self, subject):
        """Sets the subject of this Ioc.


        :param subject: The subject of this Ioc.  # noqa: E501
        :type: str
        """

        self._subject = subject

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Ioc):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Ioc):
            return True

        return self.to_dict() != other.to_dict()
