# coding: utf-8

"""
    Intel API v3 - Simplified Intel API

    FireEye Intel API - Simplified Intelligence  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@fireeye.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from fireeye.intel.configuration import Configuration


class SightingSummaryTimeline(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        '_2014_01_01': 'int',
        '_2015_08_01': 'int',
        '_2014_08_01': 'int',
        '_2014_12_01': 'int'
    }

    attribute_map = {
        '_2014_01_01': '2014-01-01',
        '_2015_08_01': '2015-08-01',
        '_2014_08_01': '2014-08-01',
        '_2014_12_01': '2014-12-01'
    }

    def __init__(self, _2014_01_01=None, _2015_08_01=None, _2014_08_01=None, _2014_12_01=None, local_vars_configuration=None):  # noqa: E501
        """SightingSummaryTimeline - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self.__2014_01_01 = None
        self.__2015_08_01 = None
        self.__2014_08_01 = None
        self.__2014_12_01 = None
        self.discriminator = None

        if _2014_01_01 is not None:
            self._2014_01_01 = _2014_01_01
        if _2015_08_01 is not None:
            self._2015_08_01 = _2015_08_01
        if _2014_08_01 is not None:
            self._2014_08_01 = _2014_08_01
        if _2014_12_01 is not None:
            self._2014_12_01 = _2014_12_01

    @property
    def _2014_01_01(self):
        """Gets the _2014_01_01 of this SightingSummaryTimeline.  # noqa: E501


        :return: The _2014_01_01 of this SightingSummaryTimeline.  # noqa: E501
        :rtype: int
        """
        return self.__2014_01_01

    @_2014_01_01.setter
    def _2014_01_01(self, _2014_01_01):
        """Sets the _2014_01_01 of this SightingSummaryTimeline.


        :param _2014_01_01: The _2014_01_01 of this SightingSummaryTimeline.  # noqa: E501
        :type: int
        """

        self.__2014_01_01 = _2014_01_01

    @property
    def _2015_08_01(self):
        """Gets the _2015_08_01 of this SightingSummaryTimeline.  # noqa: E501


        :return: The _2015_08_01 of this SightingSummaryTimeline.  # noqa: E501
        :rtype: int
        """
        return self.__2015_08_01

    @_2015_08_01.setter
    def _2015_08_01(self, _2015_08_01):
        """Sets the _2015_08_01 of this SightingSummaryTimeline.


        :param _2015_08_01: The _2015_08_01 of this SightingSummaryTimeline.  # noqa: E501
        :type: int
        """

        self.__2015_08_01 = _2015_08_01

    @property
    def _2014_08_01(self):
        """Gets the _2014_08_01 of this SightingSummaryTimeline.  # noqa: E501


        :return: The _2014_08_01 of this SightingSummaryTimeline.  # noqa: E501
        :rtype: int
        """
        return self.__2014_08_01

    @_2014_08_01.setter
    def _2014_08_01(self, _2014_08_01):
        """Sets the _2014_08_01 of this SightingSummaryTimeline.


        :param _2014_08_01: The _2014_08_01 of this SightingSummaryTimeline.  # noqa: E501
        :type: int
        """

        self.__2014_08_01 = _2014_08_01

    @property
    def _2014_12_01(self):
        """Gets the _2014_12_01 of this SightingSummaryTimeline.  # noqa: E501


        :return: The _2014_12_01 of this SightingSummaryTimeline.  # noqa: E501
        :rtype: int
        """
        return self.__2014_12_01

    @_2014_12_01.setter
    def _2014_12_01(self, _2014_12_01):
        """Sets the _2014_12_01 of this SightingSummaryTimeline.


        :param _2014_12_01: The _2014_12_01 of this SightingSummaryTimeline.  # noqa: E501
        :type: int
        """

        self.__2014_12_01 = _2014_12_01

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SightingSummaryTimeline):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SightingSummaryTimeline):
            return True

        return self.to_dict() != other.to_dict()
