# coding: utf-8

"""
    Intel API v3 - Simplified Intel API

    FireEye Intel API - Simplified Intelligence  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@fireeye.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from fireeye.intel.configuration import Configuration


class SightingSummary(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'first_seen': 'datetime',
        'last_seen': 'datetime',
        'count': 'int',
        'timeline': 'SightingSummaryTimeline',
        'segmentations': 'list[SightingSummarySegmentations]'
    }

    attribute_map = {
        'first_seen': 'first_seen',
        'last_seen': 'last_seen',
        'count': 'count',
        'timeline': 'timeline',
        'segmentations': 'segmentations'
    }

    def __init__(self, first_seen=None, last_seen=None, count=None, timeline=None, segmentations=None, local_vars_configuration=None):  # noqa: E501
        """SightingSummary - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._first_seen = None
        self._last_seen = None
        self._count = None
        self._timeline = None
        self._segmentations = None
        self.discriminator = None

        if first_seen is not None:
            self.first_seen = first_seen
        if last_seen is not None:
            self.last_seen = last_seen
        if count is not None:
            self.count = count
        if timeline is not None:
            self.timeline = timeline
        if segmentations is not None:
            self.segmentations = segmentations

    @property
    def first_seen(self):
        """Gets the first_seen of this SightingSummary.  # noqa: E501


        :return: The first_seen of this SightingSummary.  # noqa: E501
        :rtype: datetime
        """
        return self._first_seen

    @first_seen.setter
    def first_seen(self, first_seen):
        """Sets the first_seen of this SightingSummary.


        :param first_seen: The first_seen of this SightingSummary.  # noqa: E501
        :type: datetime
        """

        self._first_seen = first_seen

    @property
    def last_seen(self):
        """Gets the last_seen of this SightingSummary.  # noqa: E501


        :return: The last_seen of this SightingSummary.  # noqa: E501
        :rtype: datetime
        """
        return self._last_seen

    @last_seen.setter
    def last_seen(self, last_seen):
        """Sets the last_seen of this SightingSummary.


        :param last_seen: The last_seen of this SightingSummary.  # noqa: E501
        :type: datetime
        """

        self._last_seen = last_seen

    @property
    def count(self):
        """Gets the count of this SightingSummary.  # noqa: E501


        :return: The count of this SightingSummary.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this SightingSummary.


        :param count: The count of this SightingSummary.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def timeline(self):
        """Gets the timeline of this SightingSummary.  # noqa: E501


        :return: The timeline of this SightingSummary.  # noqa: E501
        :rtype: SightingSummaryTimeline
        """
        return self._timeline

    @timeline.setter
    def timeline(self, timeline):
        """Sets the timeline of this SightingSummary.


        :param timeline: The timeline of this SightingSummary.  # noqa: E501
        :type: SightingSummaryTimeline
        """

        self._timeline = timeline

    @property
    def segmentations(self):
        """Gets the segmentations of this SightingSummary.  # noqa: E501


        :return: The segmentations of this SightingSummary.  # noqa: E501
        :rtype: list[SightingSummarySegmentations]
        """
        return self._segmentations

    @segmentations.setter
    def segmentations(self, segmentations):
        """Sets the segmentations of this SightingSummary.


        :param segmentations: The segmentations of this SightingSummary.  # noqa: E501
        :type: list[SightingSummarySegmentations]
        """

        self._segmentations = segmentations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SightingSummary):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SightingSummary):
            return True

        return self.to_dict() != other.to_dict()
