# coding: utf-8

"""
    Intel API v3 - Simplified Intel API

    FireEye Intel API - Simplified Intelligence  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@fireeye.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from fireeye.intel.configuration import Configuration


class TrendResponseMessage(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'malware': 'TrendingObject',
        'cve': 'TrendingObject',
        'actor': 'TrendResponseMessageActor',
        'region': 'RegionTrendingObject'
    }

    attribute_map = {
        'malware': 'malware',
        'cve': 'cve',
        'actor': 'actor',
        'region': 'region'
    }

    def __init__(self, malware=None, cve=None, actor=None, region=None, local_vars_configuration=None):  # noqa: E501
        """TrendResponseMessage - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._malware = None
        self._cve = None
        self._actor = None
        self._region = None
        self.discriminator = None

        if malware is not None:
            self.malware = malware
        if cve is not None:
            self.cve = cve
        if actor is not None:
            self.actor = actor
        if region is not None:
            self.region = region

    @property
    def malware(self):
        """Gets the malware of this TrendResponseMessage.  # noqa: E501


        :return: The malware of this TrendResponseMessage.  # noqa: E501
        :rtype: TrendingObject
        """
        return self._malware

    @malware.setter
    def malware(self, malware):
        """Sets the malware of this TrendResponseMessage.


        :param malware: The malware of this TrendResponseMessage.  # noqa: E501
        :type: TrendingObject
        """

        self._malware = malware

    @property
    def cve(self):
        """Gets the cve of this TrendResponseMessage.  # noqa: E501


        :return: The cve of this TrendResponseMessage.  # noqa: E501
        :rtype: TrendingObject
        """
        return self._cve

    @cve.setter
    def cve(self, cve):
        """Sets the cve of this TrendResponseMessage.


        :param cve: The cve of this TrendResponseMessage.  # noqa: E501
        :type: TrendingObject
        """

        self._cve = cve

    @property
    def actor(self):
        """Gets the actor of this TrendResponseMessage.  # noqa: E501


        :return: The actor of this TrendResponseMessage.  # noqa: E501
        :rtype: TrendResponseMessageActor
        """
        return self._actor

    @actor.setter
    def actor(self, actor):
        """Sets the actor of this TrendResponseMessage.


        :param actor: The actor of this TrendResponseMessage.  # noqa: E501
        :type: TrendResponseMessageActor
        """

        self._actor = actor

    @property
    def region(self):
        """Gets the region of this TrendResponseMessage.  # noqa: E501


        :return: The region of this TrendResponseMessage.  # noqa: E501
        :rtype: RegionTrendingObject
        """
        return self._region

    @region.setter
    def region(self, region):
        """Sets the region of this TrendResponseMessage.


        :param region: The region of this TrendResponseMessage.  # noqa: E501
        :type: RegionTrendingObject
        """

        self._region = region

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrendResponseMessage):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TrendResponseMessage):
            return True

        return self.to_dict() != other.to_dict()
