# coding: utf-8

"""
    Helix API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.inline_object32 import InlineObject32  # noqa: E501
from openapi_client.rest import ApiException


class TestInlineObject32(unittest.TestCase):
    """InlineObject32 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineObject32(self):
        """Test InlineObject32"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.inline_object32.InlineObject32()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
